### ISSUE TITLE
Add POMI integration_alias parameter

### ISSUE THREAD

**Issue by bpschmitt** [newrelic/nri-prometheus#133]
## Is your feature request related to a problem? Please describe.

When deploying multiple instances of POMI to a single cluster it would be helpful to have a way to identify which instance metrics are sourced from.  For example, customers may want to deploy a POMI instance for scraping the EKS Control Plane endpoint and a second instance for scraping all other endpoints available in the cluster.  

Currently, I can add a custom attribute to all metrics as a workaround:

```
transformations:
    - description: "POMI Label Example"
      add_attributes:
        - metric_prefix: ""
          attributes:
            pomiName: "general"
```

This allows me to run queries like the following and facet by the `pomiName`:

```
from Metric select latest(nr_stats_integration_payload_size) as 'Payload bytes', latest(nr_stats_integration_process_duration_seconds) as 'Latest' facet scrapedTargetURL, pomiName limit 1000
```

## Feature Description

The transformation example above could be simplified by adding a config parameter:  

`integration_alias: "myInstanceName"`

## Describe Alternatives

One alternative is setting up a transformation as described above.  Another alternative would be to add the `podName` attribute to all Metrics.  `podName` is not available for the `nr_%` internal stats.

## Additional context

N/A

## Priority

Nice to Have
