### ISSUE TITLE
Metrics not exported in 1.1.0

### ISSUE THREAD

**Issue by dragos-cojocari-ibm** [newrelic/nri-prometheus#14]
I've recently upgraded from version 0.10.3 to 1.0.0 ( see issue #13 ) and I noticed that the metrics we provide are no longer scraped by NRI. Our service is annotated with `prometheus.io/scrape: true` and is being scrapped by Prometheus and the NRI scraper version 0.10.3. 

```
"metadata": {
    "name": "iot4i-prometheus-exporter-service",
    "namespace": "iot4i",
    "selfLink": "/api/v1/namespaces/iot4i/services/iot4i-prometheus-exporter-service",
    "uid": "5efc240f-2e10-11e9-8b01-0e1261484d27",
    "resourceVersion": "20017396",
    "creationTimestamp": "2019-02-11T15:19:05Z",
    "labels": {
      "app": "iot4i-prometheus-exporter",
      "chart": "iot4i-prometheus-exporter-0.1.1",
      "heritage": "Tiller",
      "release": "iot4iiot4i"
    },
    "annotations": {
      "prometheus.io/scrape": "true"
    }
  }
```

I deployed the nri-prometheus with all the default values (changing the cluster name and license key of course). So `scrape_enabled_label` is set to  "prometheus.io/scrape". If I change this to use a label specific to my service (ex: `iot4i-prometheus-exporter`) then the nri logs show `Target list for fetching metrics is empty`

What I am doing wrong here? Thank you.

**Comment by dragos-cojocari-ibm** [comment]
Quick update, I managed to get our service in the target list by creating an annotation called `iot4i/scrape` and changing the `scrape_enabled_label` to use that value. However NRI now reports a different error: 

```
 time="2019-09-25T09:50:17Z" level=info msg="Starting New Relic's Prometheus OpenMetrics Integration version 1.1.0"
time="2019-09-25T09:50:23Z" level=warning msg="fetching Prometheus: http://iot4i-prometheus-exporter-service.iot4i.svc:10080/metrics (iot4i-prometheus-exporter-service)" component=Fetcher error="Get http://iot4i-prometheus-exporter-service.iot4i.svc:10080/metrics: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
```

**Comment by douglascamata** [comment]
Hi @dragos-cojocari-ibm. I'm trying to reproduce the annotation issue from your 1st comment.

Meanwhile: the problem from your 2nd command is a client timeout. Can you get a shell into the container and try to do a timed curl (`time curl ...`) to the exporter to double check how long it takes to respond? This could also happen if there is a networking issue between the pods.

**Comment by dragos-cojocari-ibm** [comment]
thanks for the speedy reply @douglascamata . Will try your suggestion now.

Btw why is NRI trying to connect to `iot4i-prometheus-exporter-service.iot4i.svc:10080` (notice the svc) when the service URL is `iot4i-prometheus-exporter-service.iot4i:10080` ?

**Comment by dragos-cojocari-ibm** [comment]
Ran the curl from a different pod: `curl iot4i-prometheus-exporter-service.iot4i.svc:10080/metrics -w %{time_connect}:%{time_starttransfer}:%{time_total}`

Results were `0.013:5.299:5.437`

**Comment by douglascamata** [comment]
Those are both internal DNS names that resolves to the IP of the service:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
```

```bash
/ # curl my-nginx.default.svc
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
/ #
```

**Comment by dragos-cojocari-ibm** [comment]
I do not think it makes any importance but the nri-prometheus is deployed in the default namespace and our deployment is in a different namespace. I ran the curl command in the default namespace.

**Comment by douglascamata** [comment]
> I do not think it makes any importance but the nri-prometheus is deployed in the default namespace and our deployment is in a different namespace. I ran the curl command in the default namespace.

Sometimes it makes a difference, depending on the (networking) security constraints in your cluster. So it's a good thing to try running the curl from a shell in the `nri-prometheus`container. 

But from the results of you curl it seems like it takes a bit more than 5 seconds to get the full response from the endpoint. 

You can increase the client timeout for scraping endpoints to 10 seconds  by adding this to the config map used by the integration:

```yaml
cluster_name: "<your cluster name>"
scrape_timeout: "10s"
# rest of the file
...
```

For the moment you will have to restart the integration pod to reload the configuration. Soon we will be implementing hot config reload for convenience. 👍

**Comment by dragos-cojocari-ibm** [comment]
Thanks Douglas. The config file stated the default timeout was 30s so I did not think to tinker with it

```
# The HTTP client timeout when fetching data from endpoints. Defaults to 30s.
#scrape_timeout: "30s" 
```

I've uncommented the timeout line and now the error is gone. I still don't see data in the NR Dashboards but I'll give some time to fetch it and process it. Will follow-up with the results.

**Comment by douglascamata** [comment]
That statement in the config file is wrong, I will fix it.

You can add `verbose: "true"` to the configuration and you will see a log line every time data is fetched from the exporter. That should help check if it's being scraped or not and what's happening in case the fetch process is failing.

**Comment by dragos-cojocari-ibm** [comment]
Still no data is coming. Here is what I did to ensure I can isolate the data:

1. I've deleted the NRI deployment and redeployed it using a different cluster name. 
2. I've Enabled verbose logs and ran the following commands:
   - `kubectl logs deploy/nri-prometheus | grep "error emitting metrics"` - no output
   - `kubectl logs deploy/nri-prometheus | grep notification` - no output
   - in general, there are no errors in the logs.
3. In Insights:   
   - `FROM NrIntegrationError SELECT * WHERE newRelicFeature = 'Metric API'` - no output
   - `FROM Metric SELECT count(*) WHERE clusterName = 'ioti-stage1-prom' since 1 hour ago`. The result is 7K but they all appear to be metrics for the agent itself, not scrapped metrics. I searched for any of my metrics, none shows up
   - `FROM Metric SELECT * WHERE clusterName = 'ioti-stage1-prom' since 5 minutes ago`. The result is attached.

[metrics.zip](https://github.com/newrelic/nri-prometheus/files/3652069/metrics.zip)

**Comment by dragos-cojocari-ibm** [comment]
One more thing, there are many entries in the logs indicating my service is being scraped:

```
time="2019-09-25T11:12:41Z" level=debug msg="fetching URL: {http   iot4i-prometheus-exporter-service.iot4i.svc:10080 /metrics  false  }" component=Fetcher target=iot4i-prometheus-exporter-service
```

**Comment by dragos-cojocari-ibm** [comment]
I've tried both 1.1.0 and 1.0.0 with no results.  

@douglascamata can you confirm the way the metrics would be accessible in Insights has not changed since 0.10.3? I used this query back then, should it still work::

`FROM MetricRaw SELECT latest( maxwi_duration) TIMESERIES WHERE clusterName = 'ioti-stage1'`

where `maxwi_duration` is the name of the metric our service exposes in Prometheus format.

**Comment by douglascamata** [comment]
@dragos-cojocari-ibm nothing has changed about how to query the metrics in Insights since v0.10.3.

I'm still having a look at this. Do you mind sharing the configuration file you are using? It could be here or in the Zendesk ticket.

**Comment by dragos-cojocari-ibm** [comment]
Sure, I'll attach it here, stripping the license key.

**Comment by dragos-cojocari-ibm** [comment]
[nri-prometheus-latest.zip](https://github.com/newrelic/nri-prometheus/files/3652738/nri-prometheus-latest.zip)

**Comment by douglascamata** [comment]
@dragos-cojocari-ibm problem spotted!

See the snippet below from the config map in the file you attached:

```yaml
        ignore_metrics:
          # Metrics on pods and containers are being ignored as they are already collected by the New Relic Kubernetes Integration.
          - except:
            - kube_hpa_
            - kube_daemonset_
            - kube_statefulset_
            - kube_endpoint_
            - kube_service_
            - kube_limitrange
            - kube_node_
            - kube_poddisruptionbudget_
            - kube_resourcequota
            - nr_stats
```

By default all metric prefixes are being ignored, except those. This is done to protect customers from sending a lot of metrics unintentionally and getting really big bills. 

Feel free to adjust it as you see fit: you might add the prefixes of the exporter you are using there or you might even completely remove the `ignore_metrics` section, leaving the control of amount of metrics sent to New Relic only to labelling the correct resources.
