### ISSUE TITLE
Services are scraped directly instead of service endpoints

### ISSUE THREAD

**Issue by nlowe** [newrelic/nri-prometheus#27]
While services with the a `prometheus.io/scrape` annotation can be discovered, it appears that `nri-prometheus` scrapes the service itself and not service endpoints:

https://github.com/newrelic/nri-prometheus/blob/d8a8f1b1c4ff34edc8d78ceecb422cc63b29e163/internal/pkg/endpoints/kubernetes.go#L178-L192

Usually you want the [service endpoints](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints) to be discovered instead. This is useful for applications like kube/coredns that only expose the application port (`53`) on the service and not the metrics port (`9153`):

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    eks.amazonaws.com/component: kube-dns
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
#...
```

In the current configuration, `nri-prometheus` cannot scrape metrics from kube-dns because the port indicated by `prometheus.io/port` isn't exposed on the service:

```txt
default/nri-prometheus-f99cfb76b-h7hpw[nri-prometheus]: time="2019-10-29T20:26:41Z" level=warning msg="fetching Prometheus: http://kube-dns.kube-system.svc:9153/metrics (kube-dns)" component=Fetcher error="Get http://kube-dns.kube-system.svc:9153/metrics: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```

This also presents a problem for applications that ***do*** expose metrics on the same port as the service: `nri-prometheus` won't have a complete view of the application because it'll only scrape a single pod each scrape interval instead of all pods that back the service.

I could manually update the target list every time a new pod gets deployed but that's not exactly ideal.
