### ISSUE TITLE
Prometheus Config using values from Parent Chart

### ISSUE THREAD

**Issue by Kaslie** [newrelic/nri-prometheus#321]
Description:
I am unable to set prometheus config from nri-bundle values.yaml as it always use default values

How to reproduce:
```
global:
  cluster: GKE_CLUSTER
  lowDataMode: true

kube-state-metrics:
  enabled: true

prometheus:
  enabled: true
# This object values is not applied to the nri-prometheus templates/configmap.yaml
  config:
    verbose: true
    scrape_endpoints: true
    scrape_services: false

kubeEvents:
  enabled: true
```

Expected Results:
Able to set config from nri-bundle values.yaml. Example

**Comment by paologallinaharbur** [comment]
Hello, @Kaslie 
it should be `nri-prometheus` that is the name of the chart https://github.com/newrelic/helm-charts/blob/f22389eefdfaa2b1edf14a02234ecbf0f01a9ed3/charts/nri-bundle/values.yaml#L5

`prometheus` was the same of the old config just for the `.enable` that has been deprecated

**Comment by paologallinaharbur** [comment]
For example passing them directly in the command
```
helm template test ./charts/nri-bundle --set nri-prometheus.image.tag=test123 --set nri-prometheus.enabled=true --set global.cluster=test --set global.licenseKey=test | grep test123 -C5
        app.kubernetes.io/name: nri-prometheus
    spec:
      serviceAccountName: test-nri-prometheus
      containers:
      - name: nri-prometheus
        image: "newrelic/nri-prometheus:test123"
        imagePullPolicy:
        args:
          - "--configfile=/etc/nri-prometheus/config.yaml"
        ports:
          - containerPort: 8080
```
