### ISSUE TITLE
rename_attributes transformation is not renaming attribute

### ISSUE THREAD

**Issue by nosalan** [newrelic/nri-prometheus#335]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
The `rename_attributes` transformation does not rename but creates a renamed copy, do not renaming the original attribute.
## Description
After adding following transformation setting in the `newrelic-bundle-nri-prometheus` configmap
```
    transformations:
    - description: Try rename problematic labels
      rename_attributes:
        attributes:
          collector.name: "collector_name"
 ```
and restarting the `newrelic-bundle-nri-prometheus` deployment the attribute is not renamed as expected but there is a copy created.
The actual behavior is that New Relic exposes this metric:
```
 "metric": {
    "__name__": "container_fs_limit_bytes",
     "clusterName": "aks",
     "collector.name": "nri-prometheus",
     "collector.version": "2.16.3",
     "collector_name": "nri-prometheus",
     ...
```
As you can see the `collector.name` label was not renamed, instead a new label with key `collector_name` was created as a copy.
## Expected Behavior
I would expect that `rename_attributes` transformation will do the rename as its name suggests and not a copy.

## Your Environment
nri-prometheus version: 2.16.3
## Additional context
I think there is a general problem with New Relic Prometheus integration that it adds label names with dots and it violates Prometheus standards, see also https://github.com/grafana/grafana/issues/42615
