### ISSUE TITLE
Prometheus still scraping services after setting scrape_services = false

### ISSUE THREAD

**Issue by kevinp004** [newrelic/nri-prometheus#342]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
My team previously have Prometheus set up to scrape services only and found that some of the pods are not being scraped. So we wanted to switch to scrape endpoints only and disable the services scrapper entirely to avoid redundant metrics being processed as suggested [here](https://github.com/newrelic/nri-prometheus/tree/main/charts/nri-prometheus#scraping-services-and-endpoints).
Below is the New Relic configuration:
```
#Source: nri-bundle/charts/nri-prometheus/templates/configmap.yaml
kind: ConfigMap
metadata:
  name: nri-bundle-nri-prometheus-config
  namespace: newrelic
  labels:
    app.kubernetes.io/name: nri-prometheus
    helm.sh/chart: nri-prometheus-1.13.2
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/version: "3.4.0"
apiVersion: v1
data:
  config.yaml: |
    cluster_name: ${CLUSTER_FRIENDLY_NAME}
    audit: false
    insecure_skip_verify: false
    require_scrape_enabled_label_for_nodes: true
    scrape_enabled_label: prometheus.io/scrape
    scrape_timeout: 30s
    scrape_endpoints: true
    scrape_services: false
    verbose: 
```
We deployed the config above but still noticed the `services` metrics being sent to New Relic on top of the `endpoints`, which implies the services are still being scrapped. As the result below, I got both `service` and `endpoints` as the `scrapedTargetKind` which is redundant. 
```

 {
  "timestamp": 1663022940000,
  "method": "GET",
  "uri": "/health/{*path}",
  "scrapedTargetKind": "service",
  "scrapedTargetURL": "http://notification-service.someNamespace-0806.svc:9090/prometheus",
  "http_server_requests_seconds_count": {
    "type": "count",
    "count": 3
  },
  "http_server_requests_seconds_sum": null,
  "http_server_requests_seconds_max": null,
  "serviceName": "notification-service",
  "outcome": "SUCCESS",
  "scrapedTargetName": "notification-service"
},
{
  "timestamp": 1663022940000,
  "method": "GET",
  "uri": "/health/{*path}",
  "scrapedTargetKind": "endpoints",
  "scrapedTargetURL": "http://100.xx.xx.xxx:9090/prometheus",
  "http_server_requests_seconds_count": {
    "type": "count",
    "count": 3
  },
  "http_server_requests_seconds_sum": null,
  "http_server_requests_seconds_max": null,
  "serviceName": "notification-service",
  "outcome": "SUCCESS",
  "scrapedTargetName": "notification-service"
},
```
Version used: nri-prometheus 2.13.0. Configured and deployed using Helm.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
"scrapedTargetKind": "service" metrics should not show up in the New Relic since we have set scrape_services = false in the nri-Prometheus CM. This leads to redundant metrics being processed. 
I am not sure if I missed specifying anything in the configuration to avoid this behavior. Any pointers would be appreciated!

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
https://github.com/newrelic/nri-prometheus/tree/main/charts/nri-prometheus#scraping-services-and-endpoints
