### ISSUE TITLE
Ignore all metrics except set of metrics

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/nri-prometheus#344]
As a user, I want to only collect a defined set of metric names and exclude everything else. 

```
transformations:
  - description: allow
     ignore_metrics:
      - except:
        - apiserver_audit_requests_rejected_total
```

This behavior, even if it's contemplated in the tests, it's not working properly.

**Comment by paologallinaharbur** [comment]
Trying to reproducing it locally.
having:
```
  transformations:
    - description: allow
      ignore_metrics:
        - except:
            - go
```

seems to be working as expected
<img width="961" alt="Screenshot 2022-09-23 at 16 11 21" src="https://user-images.githubusercontent.com/43335750/191980185-86b6d204-d09c-4091-8ef5-d202f2258acd.png">

Moreover, there is a test covering that use case and the code seems without issues.
```go
		exceptRulesLen += len(rule.Except)
		for _, prefix := range rule.Except {
			if strings.HasPrefix(name, prefix) {
				return false
			}
		}
[...]
		// Prefixes
		prefixesLen += len(rule.Prefixes)
		for _, prefix := range rule.Prefixes {
			if strings.HasPrefix(name, prefix) {
				return true
			}
		}
```

I am trying to verify if we reproduced it locally at some point

**Comment by paologallinaharbur** [comment]
The issue is related to lowDatamode and the way multiple rules are managed.

```
	if prefixesLen > 0 || metricTypesLen > 0 {
		return false
	}
```
This is considered at the end of all rules, therefore it is enough that one had a prefix to make useless a rule with only excludes


Having:
```
transformations:
- description: allow
  ignore_metrics:
  - except:
    - apiserver_audit_requests_rejected_total
- description: Low data mode defaults
  ignore_metrics:
  - prefixes:
    - kube_
    - container_
    - machine_
    - cadvisor_
```

Then becomes similar to:
```
- description: allow
  ignore_metrics:
  - except:
    - apiserver_audit_requests_rejected_total
  - prefixes:
    - kube_
    - container_
    - machine_
    - cadvisor_
```
