### ISSUE TITLE
ignore_metrics not always working

### ISSUE THREAD

**Issue by gdziwoki** [newrelic/nri-prometheus#355]
## Description
I'm trying to exclude metrics that we do not need in NR from coredns.
this is my current setup:
```        
        transformations:
          - description: "General processing rules"
            ignore_metrics:
              - prefixes:
                  - "go_"
                  - "process_"
                  - "rest_client_"
                  - "controller_runtime_reconcile_time_"
                  - "workqueue_work_duration_seconds_bucket_"
                  - "gotk_reconcile_duration_seconds_b"
                  - "kube_"  # ignore kube-state-metrics
                  - "container_"
                  - "machine_"
                  - "cadvisor_"
                  - "node_"  # ignore prometheus-node-exporter
                  - "coredns_dns_request_duration_seconds_"
                  - "coredns_dns_response_size_bytes_"
                  - "coredns_dns_request_size_bytes_"
                  - "coredns_forward_request_duration_seconds_"
                except:
                  - "node_nf_conntrack_entries"
                  - "node_nf_conntrack_entries_limit"
 ```
But we are still getting those corns metrics in NR.
When I change it to exclude `coredns_` , then it works, but it's excluding too many metrics.

## Your Environment
k8s version 1.22
nri_prometheus version 2.16.1
