### ISSUE TITLE
Transformations.add_attributes.attributes does not maintain case

### ISSUE THREAD

**Issue by jepries** [newrelic/nri-prometheus#364]
## Description
```
transformations:
  - description: "Transformation for UCS NR metrics"
    add_attributes:
      - prefix: ""
        attributes:
          namespace: "RELEASENAMESPACE"
          nrVSAD: "RELEASEVSAD"
          nrPOC:  "RELEASEPOC"
          nrPlatform: "RELEASEPLATFORM"
          nrENVT: "RELEASEENVIRONMENT" 
    rename_attributes:
      - metric_prefix: ""
        attributes:
          nrpoc:  "nrPOC"
          nrvsad: "nrVSAD"
          nrplatform: "nrPlatform"
          nrenvt: "nrENVT"
```

the above example is what I need to do in order to create a case sensitive dimension sent to New Relic metric.
What the above does is actually send 2 attributes, example "nrvsad" and "nrVSAD"

## Expected Behavior
Maintain the case of the attribute as defined in Transformations.add_attributes.attributes

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
simply search the metrics you published in the new relic data browser, you will see Dimensions showing both the all lower case and the mixed case versions.

## Steps to Reproduce
Add any metric you like to Transformations.add_attributes.attributes that has mixed case and observe how it is posted in a new relic data search under Dimensions.

## Your Environment
Kubernetes, running 2.16.6 version of nri-prometheus

## Additional context
none

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*
