### ISSUE TITLE
Metrics of type "counter" with labels of differing values are not shipped to Newrelic

### ISSUE THREAD

**Issue by ranimufid** [newrelic/nri-prometheus#39]
**Background**
I am currently attempting to scrape and push pulsar component prometheus [metrics](https://pulsar.apache.org/docs/en/reference-metrics/) into Newrelic. 

- nri-prometheus image version: `newrelic/nri-prometheus:1.3.0`

- config map:

```
scrape_duration: "20s"
verbose: false
insecure_skip_verify: true
scrape_enabled_label: "prometheus.io/scrape"
require_scrape_enabled_label_for_nodes: true
```

**Issue 1** 🚨 
It seems that the `nri-prometheus` is unable to process metrics with labels of differing values for type `counter`:

**_Does not arrive at Newrelic_** 👎 
```
bookie_journal_JOURNAL_SYNC_count{success="false"} 0
bookie_journal_JOURNAL_SYNC_count{success="true"} 24684154
```

_**Arrives at Newrelic**_ 👍 
```
bookie_WRITE_BYTES 20991304885
```

**Issue 2** 🚨 
We also see tonnes of error messages in the logs for metrics of type `summary` with `NaN` values

Example
```
{"err":"invalid float is NaN","message":"invalid gauge field","name":"bookie_journal_JOURNAL_CREATION_LATENCY.percentiles"}
```
And the corresponding metric values:

```
# TYPE bookie_journal_JOURNAL_CREATION_LATENCY summary
bookie_journal_JOURNAL_CREATION_LATENCY{success="false",quantile="0.5"} NaN
bookie_journal_JOURNAL_CREATION_LATENCY{success="false",quantile="0.75"} NaN
bookie_journal_JOURNAL_CREATION_LATENCY{success="false",quantile="0.95"} NaN
bookie_journal_JOURNAL_CREATION_LATENCY{success="false",quantile="0.99"} NaN
bookie_journal_JOURNAL_CREATION_LATENCY{success="false",quantile="0.999"} NaN
bookie_journal_JOURNAL_CREATION_LATENCY{success="false",quantile="0.9999"} NaN
bookie_journal_JOURNAL_CREATION_LATENCY{success="false",quantile="1.0"} -Infinity
```

Help regarding understanding both the above behaviours would be greatly appreciated :)!

**Comment by douglascamata** [comment]
Hi @ranimufid, 

**On Issue 1**:

Do you know if these counters are changing over time? 

Counters are stored in New Relic by the variation in the metric between two different runs of the integration. For example, if we get `24684154` on the first run for a given metric and the value is incremented by 1 in the second run, `1` will be sent to New Relic. If the value doesn't change, zeroes will be sent. 

I'm working on confirming if this is the intended behaviour.

**On issue 2**

NaNs and infinities are not sent to New Relic. This integration using the [go-telemetry-sdk](https://github.com/newrelic/newrelic-telemetry-sdk-go), and in the [Telemetry SDK specs](https://github.com/newrelic/newrelic-telemetry-sdk-specs/blob/8c6a23ef8a942e8c44824c4835d8adb7534d2e76/validation.md) the following in stated: 

> (...) in languages where NaN or Infinity can be represented these values may be stored but can not be correctly marshalled to JSON and thus are dropped when JSON marshalling occurs because it violates the safety of the payload.

**Comment by ranimufid** [comment]
Thanks for your response @douglascamata!

Noted on Issue 2.

**Issue 1**
I can confirm that the metric values change over time

```
#Tue Mar 10 15:38:08 UTC 2020
bookie_journal_JOURNAL_SYNC_count{success="false"} 0
bookie_journal_JOURNAL_SYNC_count{success="true"} 210739
# Tue Mar 10 15:38:20 UTC 2020
bookie_journal_JOURNAL_SYNC_count{success="false"} 0
bookie_journal_JOURNAL_SYNC_count{success="true"} 210740
```

The problem also is that the metric doesn't show up in newrelic at all. I can't find any instance of `bookie_journal_JOURNAL_SYNC_count`. This is the NRQL I used to verify:
```
FROM Metric SELECT uniques(metricName) where clusterName='aud-pulsar-testing' and metricName='bookie_journal_JOURNAL_SYNC_count'
```

**Comment by douglascamata** [comment]
Interesting!

I cannot reproduce it locally using the exact same configuration as you. Do you mind checking for for ingest errors using the following query: `SELECT count(*) FROM NrIntegrationError WHERE newRelicFeature ='Metrics' facet category, message limit 1000 since 24 hours ago`?

**Comment by ranimufid** [comment]
I get the following message on executing the query you shared:
```
No events found -- do you have the correct event type and time range?
```

In my initial attempt, I ran nri-prometheus as a kubernetes deployment. I've now started it as a docker container that is scraping some remote endpoints. Sadly I still observe the same behaviour 😢 This is my new config:
```
cluster_name: "aud-pulsar-testing"
scrape_duration: "20s"
scrape_timeout: "5s"
verbose: true
insecure_skip_verify: false
scrape_enabled_label: "prometheus.io/scrape"
require_scrape_enabled_label_for_nodes: false

targets:
- description: Pulsar Broker URLs
  urls: ["http://url:8080/metrics/","http://url:8080/metrics/","http://url:8080/metrics/"]
- description: Bookkeeper URLs
  urls: ["http://url:8000/metrics","http://url:8000/metrics","http://url:8000/metrics"]
- description: Zookeeper URLs
  urls: ["http://url:8000/metrics","http://url:8000/metrics","http://url:8000/metrics"]
```

When attempting to reproduce the issue locally on your end, did you supply your code with the same metrics I shared?
```
bookie_journal_JOURNAL_SYNC_count{success="false"} 0
bookie_journal_JOURNAL_SYNC_count{success="true"} 210739
```

Is there anything that I can provide you which can be of help in troubleshooting this issue?

**Comment by douglascamata** [comment]
I'm trying it locally with exactly these two metrics, giving them the `counter` type, and using a "static file exporter": 

```yaml
############################################
# Prometheus exporter for K8s that serves
# metrics from a plain text file
############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: from-file-prometheus-exporter
  labels:
    app: from-file-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: from-file-prometheus-exporter
  template:
    metadata:
      labels:
        app: from-file-prometheus-exporter
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: from-file-prometheus-exporter
          image: python:alpine3.9
          env:
            - name: METRICS_FILE_URL
              value: "<URL_TO_DOWNLOAD_FILE>" # You can use private gist url.
          ports:
            - name: metrics
              containerPort: 8080
          command: ["/bin/sh","-c"]
          # The reason of using a URL instead of a config map is that the latest has a limitation of up to 1MB
          args: ["wget $METRICS_FILE_URL -O /etc/from-file-prometheus-exporter/metrics; python -m http.server -b 0.0.0.0 -d /etc/from-file-prometheus-exporter/ 8080"]
          volumeMounts:
            - mountPath: /etc/from-file-prometheus-exporter/
              name: metrics-dir
          readinessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 15
      volumes:
        - name: metrics-dir
          emptyDir: {}

```

My static file looks like this:

```
# TYPE bookie_journal_JOURNAL_SYNC_count counter
bookie_journal_JOURNAL_SYNC_count{success="false"} 0
bookie_journal_JOURNAL_SYNC_count{success="true"} 24684154
```

And my `config.yml` file in the config map has this:

```yaml
    cluster_name: "zdcamata-pomi"
    scrape_duration: "20s"
    scrape_timeout: "1m"
    verbose: true
    scrape_enabled_label: "prometheus.io/scrape"
    require_scrape_enabled_label_for_nodes: true
    transformations:
      - description: "General processing rules"
        add_attributes:
          - metric_prefix: ""
            attributes:
              my_extra_attr: "my-value"
        rename_attributes:
          - metric_prefix: ""
            attributes:
              container_name: "containerName"
              pod_name: "podName"
              namespace: "namespaceName"
              node: "nodeName"
              container: "containerName"
              pod: "podName"
              deployment: "deploymentName"
        ignore_metrics:
          - prefixes:
              - go_
              - http_
              - process_
```

Can you try this, please, and tell me if it works? Also have a look at the logs to see if there is something weird -- it will be in verbose mode.

Signing off until tomorrow's working hours in CET. 👋
