### ISSUE TITLE
Ignore metrics partially works

### ISSUE THREAD

**Issue by shachar-ash** [newrelic/nri-prometheus#449]
## Description

We are using nri-prometheus and we configured it to drop the following metrics:
```
            transformations:
              - description: 'Filter metrics'
                ignore_metrics:
                  - prefixes:
                    - 'go_'
                    - 'coredns_'
                    - 'splunk_'
                    - 'envoy_cluster_external_upstream_rq_time_'
                    - 'nginx_ingress_controller_ingress_upstream_latency_seconds_'
```

Unfortunately, only some of the metrics are dropped. For example, we still get the following metrics:
```
envoy_cluster_external_upstream_rq_time_bucket
nginx_ingress_controller_ingress_upstream_latency_seconds_count
```

## Expected Behavior
I expect all metrics with the provided prefixes to not reach NR.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

I went through the logs of `nri-prometheus`, there was no error log that indicates an issue. 
The only logs I saw were about scraping unavailable endpoints, for example:
```
time="2023-10-30T19:32:40Z" level=warning msg="error while scraping target" component=Fetcher error="Get \"http://1.2.3.4:9253/metrics\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

But those logs are not related to the metrics I'm trying to exclude.

## Steps to Reproduce
Use the above transformations block.

## Your Environment
Helm chart version: `nri-prometheus-2.1.17`
nri-prometheus version: 2.18.4
 
Any help would be highly appreciated!

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*
