### ISSUE TITLE
Support regex in ignore_metrics

### ISSUE THREAD

**Issue by shachar-ash** [newrelic/nri-prometheus#471]
### Description
Currently, when metrics are excluded and we want to add an exception for a subset of metrics, the only option is to add an exception for a prefix.

This is a problem, as it forces us to keep metrics we don't necessarily want. For example, let's look at the following rules:
```
               ignore_metrics:
                  - prefixes:
                    - 'envoy_'
                    except:
                      - 'envoy_cluster_external_upstream_rq'
```

In the above example, the only metric I want to keep is `envoy_cluster_external_upstream_rq`, but when adding this `except` clause, I am also forced to keep every other metric with the prefix `envoy_cluster_external_upstream_rq`, so I'll end up having other metrics I don't want, like `envoy_cluster_external_upstream_rq_time` for example.

### Acceptance Criteria
Add regex support, instead of only supporting metrics prefixes.

### Estimates
T-shirt size: S = 1-3 days
