### ISSUE TITLE
NRI Prometheus using enormous amounts of resources

### ISSUE THREAD

**Issue by hero-david** [newrelic/nri-prometheus#475]
## Description

We had to bump up the default resource values when deploying the chart because we were hitting OOM errors. We've increased the resource limits significantly, however the collector is still starting to consume resources on the host it is running on:
![image](https://github.com/newrelic/nri-prometheus/assets/108767410/de6e6dca-1404-4e93-ba4e-4d5ddf58fcbc)

We bumped the CPU up to 1 core and it manages to consistently hit the limit on our 2 core machine.
![image](https://github.com/newrelic/nri-prometheus/assets/108767410/aff1f3ab-4a43-4e44-a05f-dc91fc324b81)

## Expected Behavior

I would not expect such high CPU usage, given the github issue referenced in the additional context segment lists high as exceeding 400m.

## Your Environment

We're running an AKS cluster with 306 pods across all namespaces.

```
➜  ~ kubectl version
...
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"5d130885b649a257745a53ef52b6043885595d46", GitTreeState:"clean", BuildDate:"2023-11-02T19:48:17Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
➜  ~ k get deployment -n newrelic newrelic-nri-prometheus -oyaml | grep 'image: '
        image: newrelic/nri-prometheus:2.21.0
```

Has been installed via the nri-bundle helm chart with the following values:

```yaml

global:
  lowDataMode: true
  ...
  
nri-prometheus:
  config:
    percentiles:
    - 50
    - 95
    - 99
    scrape_endpoints: true
    scrape_services: false
    transformations:
    - copy_attributes:
      - from_metric: kube_hpa_labels
        match_by:
        - namespace
        - hpa
        to_metrics: kube_hpa_
      - from_metric: kube_daemonset_labels
        match_by:
        - namespace
        - daemonset
        to_metrics: kube_daemonset_
      - from_metric: kube_statefulset_labels
        match_by:
        - namespace
        - statefulset
        to_metrics: kube_statefulset_
      - from_metric: kube_endpoint_labels
        match_by:
        - namespace
        - endpoint
        to_metrics: kube_endpoint_
      - from_metric: kube_service_labels
        match_by:
        - namespace
        - service
        to_metrics: kube_service_
      - from_metric: kube_node_labels
        match_by:
        - namespace
        - node
        to_metrics: kube_node_
      description: Uncomment if running New Relic Kubernetes Integration
      ignore_metrics:
      - prefixes:
        - kube_daemonset_
        - kube_deployment_
        - kube_endpoint_
        - kube_namespace_
        - kube_node_
        - kube_persistentvolume_
        - kube_pod_
        - kube_replicaset_
        - kube_service_
        - kube_statefulset_
      rename_attributes:
      - attributes:
          container: containerName
          container_name: containerName
          deployment: deploymentName
          namespace: namespaceName
          node: nodeName
          pod: podName
          pod_name: podName
        metric_prefix: ""
  enabled: true
  image:
    tag: 2.21.0
  nodeSelector:
    role: dedicated
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 500Mi
```

## Additional context

High CPU consumption is listed in this issue as > 0.4 cores, we're well past that!
https://github.com/newrelic/nri-prometheus/issues/132
