### ISSUE TITLE
issue with metrics on 2.0.0

### ISSUE THREAD

**Issue by 0011blindmice** [newrelic/nri-prometheus#57]
Hello,

We've recently updated our clusters to use the new 2.0.0 image of nri-prometheus, and we're seeing a lot of errors being dumped in the pod logs, as well as an absence of metrics on our dashboards since the change.

We're seeing a large amount of errors similar to this, for various different metric names:
```shell
2020/07/09 21:42:45.138144 {"err":"invalid float is NaN","message":"invalid gauge field","name":"apiserver_request_latencies_summary"}
```

I've left our configuration as it was in version 1.5.0. Here are the contents of the file:
```yaml
    # The name of your cluster. It's important to match other New Relic products to relate the data.
    cluster_name: eks-observability-hvuv-npge
    # How often the integration should run. Defaults to 30s.
    scrape_duration: "1m"
    # The HTTP client timeout when fetching data from endpoints. Defaults to 5s.
    scrape_timeout: "20s"
    # Wether the integration should run in verbose mode or not. Defaults to false.
    verbose: false
    # Wether the integration should skip TLS verification or not. Defaults to false.
    insecure_skip_verify: false
    # The label used to identify scrapable targets. Defaults to "prometheus.io/scrape".
    scrape_enabled_label: "prometheus.io/scrape"
    # Whether k8s nodes need to be labelled to be scraped or not. Defaults to true.
    require_scrape_enabled_label_for_nodes: false

    targets:
     - description: Kubernetes API Server
       urls: []

    #targets:
    #  - description: Secure etcd example
    #    urls: ["https://192.168.3.1:2379", "https://192.168.3.2:2379", "https://192.168.3.3:2379"]
    #    tls_config:
    #      ca_file_path: "/etc/etcd/etcd-client-ca.crt"
    #      cert_file_path: "/etc/etcd/etcd-client.crt"
    #      key_file_path: "/etc/etcd/etcd-client.key"

    # Proxy to be used by the emitters when submitting metrics. It should be
    # in the format [scheme]://[domain]:[port].
    # The emitter is the component in charge of sending the scraped metrics.
    # This proxy won't be used when scraping metrics from the targets.
    # By default it's empty, meaning that no proxy will be used.
    emitter_proxy: http://proxy.ebiz.verizon.com:80/

    # Certificate to add to the root CA that the emitter will use when
    # verifying server certificates.
    # If left empty, TLS uses the host's root CA set.
    # emitter_ca_file: "/path/to/cert/server.pem"

    # Whether the emitter should skip TLS verification when submitting data.
    # Defaults to false.
    # emitter_insecure_skip_verify: false

    # Histogram support is based on New Relic's guidelines for higher
    # level metrics abstractions https://github.com/newrelic/newrelic-exporter-specs/blob/master/Guidelines.md.
    # To better support visualization of this data, percentiles are calculated
    # based on the histogram metrics and sent to New Relic.
    # By default, the following percentiles are calculated: 50, 95 and 99.
    #
    percentiles:
      - 50
      - 90
      - 95
      - 99

    transformations:
      - description: "General processing rules"
      #  rename_attributes:
      #    - metric_prefix: ""
      #      attributes:
      #        container_name: "containerName"
      #        pod_name: "podName"
      #        namespace: "namespaceName"
      #        node: "nodeName"
      #        container: "containerName"
      #        pod: "podName"
      #        deployment: "deploymentName"
      #  ignore_metrics:
      #    # Metrics on pods and containers are being ignored as they are already collected by the New Relic Kubernetes Integration.
      #    - except:
      #      - kube_hpa_
      #      - kube_daemonset_
      #      - kube_statefulset_
      #      - kube_endpoint_
      #      - kube_service_
      #      - kube_limitrange
      #      - kube_node_
      #      - kube_poddisruptionbudget_
      #      - kube_resourcequota
      #      - nr_stats
        copy_attributes:
          - from_metric: "kube_hpa_labels"
            to_metrics: "kube_hpa_"
            match_by:
              - namespace
              - hpa
          - from_metric: "kube_daemonset_labels"
            to_metrics: "kube_daemonset_"
            match_by:
              - namespace
              - daemonset
          - from_metric: "kube_statefulset_labels"
            to_metrics: "kube_statefulset_"
            match_by:
              - namespace
              - statefulset
          - from_metric: "kube_endpoint_labels"
            to_metrics: "kube_endpoint_"
            match_by:
              - namespace
              - endpoint
          - from_metric: "kube_service_labels"
            to_metrics: "kube_service_"
            match_by:
              - namespace
              - service
          - from_metric: "kube_node_labels"
            to_metrics: "kube_node_"
            match_by:
              - namespace
              - node
```

We have another deployment purely scraping the Kubernetes API Server that we've upgraded which is also facing the same problem.  It has the same config, save for a different scrape tag and having the target URL filled in.
