### ISSUE TITLE
Helm deployed agent does not fetch metrics until restart

### ISSUE THREAD

**Issue by pstatham** [newrelic/nri-prometheus#65]
We're deploying `nri-prometheus` as a subchart of our own app's helm chart. For some reason `nri-prometheus` is not fetching our app's metrics  until after we `kubectl delete` it's pod. When the pod is recreated, we can see from it's logs that our app's pod gets added to the fetcher.

Any ideas?

Relevant part of our `Chart.yaml`:
```yaml
dependencies:
  - name: nri-prometheus
    version: 1.2.0
    repository: https://helm-charts.newrelic.com
    condition: nri-prometheus.install
```
